# Generated by Django 3.2 on 2021-04-17 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210417_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product/'),
            preserve_default=False,
        ),
    ]
