# Generated by Django 3.2 on 2021-04-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210417_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='p_material',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Platinum', 'Platimnum'), ('Brass', 'Brass'), ('Bangles', 'Bangles'), ('Diamond', 'Diamond')], max_length=200),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sub_cate',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Chain', 'Chain'), ('Bracelet', 'Bracelet'), ('Anklet', 'Anklet'), ('Barrette', 'Barrette'), ('Belt buckle', 'Belt buckle'), ('Belly chain', 'Belly chain'), ('Bindi', 'Bindi'), ('Bolo tie', 'Bolo tie'), ('Bracelet', 'Bracelet'), ('Brooch', 'Brooch'), ('Earrings', 'Earrings'), ('Ear cuff', 'Ear cuff'), ('Fascinator', 'Fascinator'), ('Hairpin', 'Hairpin'), ('Hatpin', 'Hatpin')], max_length=200),
        ),
    ]
