# Generated by Django 3.2 on 2021-04-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210417_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='p_size',
            field=models.CharField(default='X', max_length=20),
        ),
    ]
