# Generated by Django 3.2 on 2021-04-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_productmodel_p_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='p_size',
        ),
    ]
