# Generated by Django 3.2 on 2021-04-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='p_type',
            field=models.CharField(choices=[('Single Material', 'Single Material'), ('Double Material', 'Double Material'), ('Mix Material', 'Mix Material')], default='Single Material', max_length=200),
        ),
    ]
