# Generated by Django 3.2 on 2021-04-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productmodel_p_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sell_price',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='sub_cate',
            field=models.CharField(choices=[('Ring', 'Ring'), ('Anklet', 'Anklet'), ('Barrette', 'Barrette'), ('Belt buckle', 'Belt buckle'), ('Belly chain', 'Belly chain'), ('Bindi', 'Bindi'), ('Bolo tie', 'Bolo tie'), ('Bracelet', 'Bracelet'), ('Brooch', 'Brooch'), ('Earrings', 'Earrings'), ('Ear cuff', 'Ear cuff'), ('Fascinator', 'Fascinator'), ('Hairpin', 'Hairpin'), ('Hatpin', 'Hatpin')], max_length=200),
        ),
    ]
