# Generated by Django 3.2 on 2021-04-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210417_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='p_mode',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('New Arrival', 'New Arrival'), ('Running', 'Running')], default='Running', max_length=100),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='p_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Out of Stock', 'Out of Stock'), ('limited stock', 'limited stock')], default='Available', max_length=100),
        ),
    ]
